### ISSUE TITLE
'SDWebImage/UIImageView+WebCache.h' file not found on build

### ISSUE THREAD

**Issue by hummerh2** [SlayterDev/RadiumBrowser#13]
Followed the instructions in the readme including ```pod install```. 
When running build in xcode receive 'SDWebImage/UIImageView+WebCache.h' file not found.

```
pod install
Analyzing dependencies
Downloading dependencies
Using BSColorUtils (1.0.2)
Using GCDWebServer (3.4.2)
Using Highlightr (1.1.0)
Using LUAutocompleteView (2.0.0)
Using Realm (2.10.0)
Using RealmSwift (2.10.0)
Using SDWebImage (3.8.2)
Using SnapKit (3.2.0)
Using Then (2.2.1)
Using WaitForIt (2.0.0)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There are 9 dependencies from the Podfile and 10 total pods installed.
```

macOS Sierra
Version 9.1 (9B55)

![screen shot 2017-11-02 at 9 18 27 pm](https://user-images.githubusercontent.com/14918418/32376506-5af68ce8-c07b-11e7-8333-68fe54496d76.png)

**Comment by SlayterDev** [comment]
While I was not able to recreate your specific issue, I did stumble upon a few pod related issues while attempting a clean setup of the project. I have resolved these issues and encourage you to try the [development](https://github.com/SlayterDev/RadiumBrowser/tree/development) branch. Also make sure you are using the `xcworkspace` and not the `xcodeproj`.

**Comment by SlayterDev** [comment]
@hummerh2 are you still having issues with this?

**Comment by hummerh2** [comment]
Not having this issue on development branch now. Thanks!

However i did run into a couple more issues I will see if i can work through this week.

**Comment by SlayterDev** [comment]
Awesome! 👍
